<a href="https://colab.research.google.com/github/Um-king/orm/blob/main/lms_%EC%98%81%EC%83%81_%EA%B5%90%EC%9C%A1_1%EB%B6%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 크롤링

## URL(Uniform Resource Locator)
* 자원이 어디 있는지 알려주기 위한 규약
* 흔히 웹사이트 주소로 알고 있지만, URL은 웹 사이트 주소뿐만 아니라 컴퓨터 네트워크상의 자원을 모두 나타낼 수 있다.
* 그 주소에 접속하려면 해당 URL에 맞는 프로토콜을 알아야하고, 그와 동일한 프로토콜로 접속(FTP 프로토콜인 경우에는 FTP 클라이언트를 이용해야 하고, HTTP인 경우에는 웹 브라우저를 이용해야한다. 텔넷의 경우에는 텔넷 프로그램을 이용해서 접속)

## HTTP(Hypertext Transger Protocol)
* HTML, XML, Javascript, 오디오, 비디오, 이미지, PDF, Etc
* 요청 또는 상태 라인 / 해더(생략가능) / 빈줄(해더의 끝) / 바디(생략가능)

### HTTP 처리방식
* GET : 리소스 취득(? 뒤에 이어붙이는 방식 - 작은 값들)
* POST : 리소스 생성(Body에 붙이는 방식 - 상대적으로 큰 용량)
* PUT, DELETE, HEAD, OPTIONS, TRACE, CONNECT

### 상태코드
* 200
* 201
* 301
* 403
* 404
* 500
* 503


---


* 200번대 : 성공을 의미
* 400번대 : 클라이언트 오류, 요청 문법이 잘못되었거나 요청을 처리할 수 x
* 500번대 : 서버오류, 서버가 명백히 유효한 요청에 대해 충족을 실패했다

## requests

In [28]:
import requests
from bs4 import BeautifulSoup

html = requests.get('http://www.paullab.co.kr/stock.html')
html

In [29]:
html.encoding = 'utf-8' # 인코딩 변경 -> 한국어 깨지는것을 방지

In [31]:
html.text

'<!DOCTYPE html>\n<html lang="en">\n\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <meta http-equiv="X-UA-Compatible" content="ie=edge">\n  <title>크롤링 연습 페이지</title>\n  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">\n  <link rel="stylesheet" type="text/css" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous">\n  <style>\n    h1{\n      margin: 2rem;\n    }\n\n    h1>span{\n      font-size: 1rem;\n    }\n\n    h2 {\n      font-size: 1.5rem;\n      font-weight: bold;\n      margin-bottom: 1rem;\n      margin-top: 5rem;\n    }\n\n    .heading-top {\n      margin-top: 1rem;\n    }\n\n    .main {\n      width: 100%;\n      margin: 0 auto;\n      text-align: center;\n    }\n\n    table {\n      width: 100%;\n    }\n\n    a {\n      /* color: inherit; */\n      cursor: pointer;\n      text-decoration: none;\n    }\n\n    a:hover {\n      color: #000;\n      text-decoration: none;\n    }\n\n    em {\n      font: inherit;\n    }\n\n    #information {\n      padding: 15px;\n      margin-bottom: 50px;\n    }\n\n    #information h2 {\n      padding-bottom: 20px;\n    }\n\n    #information .wrap {\n      display: flex;\n      align-items: center;\n\n    }\n\n    #information .cat-img img {\n      width: 90%;\n    }\n\n    #information .tables {\n      border: 1px solid #dbdbdb;\n      padding: 20px 10px;\n    }\n\n    #information table {\n      position: relative;\n      width: 100%;\n      padding: 10px;\n      /* border-bottom: 1.5px dashed #dbdbdb; */\n      align-items: center;\n      border-collapse: separate;\n    }\n\n    #information tr {\n      text-align: left;\n      align-items: center;\n    }\n\n    #information th {\n      font-size: 14px;\n      align-items: center;\n      padding-right: 10px;\n      font-weight: normal;\n    }\n\n    #information td {\n      text-align: right;\n      font-size: 13px;\n    }\n\n    #information .strong {\n      font-weight: bold;\n    }\n\n    .bar {\n      color: #dbdbdb;\n      font-size: 14px;\n    }\n\n    .link_site i {\n      color: #000;\n    }\n\n    .link_site:hover {\n      text-decoration: underline;\n    }\n\n    .link_site i {\n      color: #dbdbdb;\n      padding-left: 5px;\n    }\n\n    .help {\n      font-size: 5px;\n      font-weight: bold;\n      color: rgb(91, 100, 103);\n      border: 1px solid #888;\n      padding: 0px 3px;\n    }\n\n    .lyr_section {\n      position: absolute;\n      font-size: 13px;\n      background-color: #FFF;\n      padding: 10px;\n      width: 250px;\n      border: 1px solid #888;\n      line-height: 1.5;\n      margin-top: 10px;\n      z-index: 999;\n    }\n\n    #helpPannel5 p {\n      color: #888;\n      margin: 0;\n    }\n\n    .arrow {\n      position: absolute;\n      left: 75px;\n      top: 0;\n      width: 10px;\n      height: 10px;\n      border-top: 1px solid #888;\n      border-right: 1px solid #888;\n      background-color: #FFF;\n      margin-top: -6px;\n      -webkit-transform: rotate(-45deg);\n      transform: rotate(-45deg);\n    }\n\n    .border-style {\n      border-bottom: 1.5px dashed #dbdbdb;\n    }\n\n  </style>\n</head>\n\n<body>\n  <!-- 메뉴바, 로고 이미지는 logo-icon.png -->\n  <nav>\n    <div class="container-fluid">\n      <div class="row pt-3">\n        <div class="col-12">\n          <a href="https://www.paullab.co.kr">\n            <img src="images/logo-icon.png" alt="logo" width="50px">\n          </a>\n        </div>\n      </div>\n    </div>\n  </nav>\n  <h1 class="sr-only">크롤링 연습용 페이지</h1>\n\n  <div id="information" class="main container">\n    <h2 class="heading-top">(주)캣네생선</h2>\n    <p>해당 페이지는 주식 크롤링 연습용 페이지입니다. 책 크롤링 연습을 하고 싶다면 <a href="https://paullab.co.kr/bookservice/">책 크롤링</a> 페이지로 이동하세요.</p>\n    <div class="wrap main row">\n      <div class="cat-img col-md-7">\n        <img src="images/cats_stock.png" alt="(주)캣네가게 주가" class="img-fluid">\n      </div>\n      <div class="tables col-md-5">\n        <table summary="시가총액 정보" class="border-style">\n          <tr>\n              <th class="strong" scope="row">시가총액</th>\n              <!-- 공백은 의도적으로 넣은 것입니다. -->\n              <td class="strong"><em id="_market_sum">349조 2,323</em>억원</td>\n          </tr>\n          <tr>\n              <th scope="row">\n                  <a class="link_site" href="#">시가총액순위<i class="fas fa-caret-right"></i></a>\n              </th>\n              <!-- 공백은 의도적으로 넣은 것입니다. -->\n              <td>위니브월드 <em id="_market_sum">1</em>위</td>\n          </tr>\n          <tr>\n              <th scope="row">상장주식수</th>\n              <!-- 공백은 의도적으로 넣은 것입니다. -->\n              <td><em id="_market_sum">5,969,782,550</em></td>\n          </tr>\n        </table>\n\n        <table summary="업종상세 정보" class="border-style">\n            <tr>\n                <th class="strong" scope="row">현재가</th>\n                <td class="strong"><em id="_market_sum">349조 2,323</em>억원</td>\n            </tr>\n            <tr>\n                <th scope="row">52주 최고 <span class="bar">l</span> 최저</th>\n                <td>\n                    <em>62,800</em>\n                    <span class="bar">l</span>\n                    <em>42,300</em>\n                </td>\n            </tr>\n            <tr>\n                <th scope="row">배당수익률 <span class="bar">l</span><span> 2040.12</span>\n                  <a class="help" href="#" alt="배당수익률 상세설명"><em>?</em></a>\n                  <div class="lyr_section" style="display:none">\n                    <div id="helpPannel5" class="tooltip_lyr dividend_layer">\n                      <strong>배당수익률 = (배당금 / 현재가) x 100</strong>\n                      <p>배당금은 최근 결산연도 기준의 중간배당을 포함한 총 배당금입니다.</p>\n                      <span class="arrow"></span>\n                    </div>\n                  </div>\n                </th>\n                <td>\n                    <em id="_dvr">2.42</em>%\n                </td>\n            </tr>\n        </table>\n\n        <table>\n            <tr>\n                <th class="strong" scope="row">매출</th>\n                <!-- <td>22조 1,250억원</td> -->\n                <td class="strong">22,125,034,978,750원</td>\n            </tr>\n            <tr>\n                <th scope="row">비용</th>\n                <!-- <td>19조 2,238억원</td> -->\n                <td>19,223,803,154,781원</td>\n            </tr>\n            <tr>\n                <th scope="row">순익</th>\n                <!-- <td><em id="_market_sum">2조 9,012억원</em></td> -->\n                <td><em id="_market_sum">2,901,231,823,969원</em></td>\n            </tr>\n        </table>\n      </div>\n\n    </div>\n\n  </div>\n\n  <div class="main container">\n    <h2 id="제주코딩베이스캠프연구원">제주코딩베이스캠프 연구원</h2>\n    <table class="table table-hover">\n      <tbody>\n        <tr>\n          <th scope="col">날짜</th>\n          <th scope="col">종가</th>\n          <th scope="col">전일비</th>\n          <th scope="col">시가</th>\n          <th scope="col">고가</th>\n          <th scope="col">저가</th>\n          <th scope="col">거래량</th>\n        </tr>\n\n\n\n        <tr>\n          <td align="center "><span class="date ">2040.10.23</span></td>\n          <td class="num "><span>6,650</span></td>\n          <td class="num ">\n            <img src="ico_up.gif " width="7 " height="6 " style="margin-right:4px; " alt="상승 "><span>\n                            20\n                        </span>\n          </td>\n          <td class="num "><span>6,590</span></td>\n          <td class="num "><span>6,830</span></td>\n          <td class="num "><span>6,580</span></td>\n          <td class="num "><span>398,421</span></td>\n        </tr>\n\n\n\n        <tr>\n          <td align="center"><span class="date">2040.10.22</span></td>\n          <td class="num"><span>6,630</span></td>\n          <td class="num">\n            <img src="ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n                            190\n                        </span>\n          </td>\n          <td class="num"><span>6,830</span></td>\n          <td class="num"><span>6,930</span></td>\n          <td class="num"><span>6,530</span></td>\n          <td class="num"><span>919,571</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.21</span></td>\n          <td class="num"><span>6,820</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            390\n                        </span>\n          </td>\n          <td class="num"><span>6,440</span></td>\n          <td class="num"><span>6,890</span></td>\n          <td class="num"><span>6,360</span></td>\n          <td class="num"><span>1,678,055</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.18</span></td>\n          <td class="num"><span>6,430</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            480\n                        </span>\n          </td>\n          <td class="num"><span>6,020</span></td>\n          <td class="num"><span>6,620</span></td>\n          <td class="num"><span>5,970</span></td>\n          <td class="num"><span>2,168,857</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.17</span></td>\n          <td class="num"><span>5,950</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            20\n                        </span>\n          </td>\n          <td class="num"><span>6,100</span></td>\n          <td class="num"><span>6,180</span></td>\n          <td class="num"><span>5,840</span></td>\n          <td class="num"><span>1,982,922</span></td>\n        </tr>\n\n        <tr>\n          <td align="center"><span class="date">2040.10.16</span></td>\n          <td class="num"><span>5,930</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            290\n                        </span>\n          </td>\n          <td class="num"><span>5,620</span></td>\n          <td class="num"><span>5,930</span></td>\n          <td class="num"><span>5,350</span></td>\n          <td class="num"><span>839,434</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.15</span></td>\n          <td class="num"><span>5,640</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            260\n                        </span>\n          </td>\n          <td class="num"><span>5,370</span></td>\n          <td class="num"><span>5,660</span></td>\n          <td class="num"><span>5,300</span></td>\n          <td class="num"><span>702,104</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.14</span></td>\n          <td class="num"><span>5,380</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            340\n                        </span>\n          </td>\n          <td class="num"><span>5,060</span></td>\n          <td class="num"><span>5,420</span></td>\n          <td class="num"><span>5,060</span></td>\n          <td class="num"><span>764,800</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.11</span></td>\n          <td class="num"><span>5,040</span></td>\n          <td class="num">\n            <img src="ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n                            60\n                        </span>\n          </td>\n          <td class="num"><span>5,100</span></td>\n          <td class="num"><span>5,170</span></td>\n          <td class="num"><span>5,020</span></td>\n          <td class="num"><span>134,558</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.10</span></td>\n          <td class="num"><span>5,100</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            50\n                        </span>\n          </td>\n          <td class="num"><span>5,000</span></td>\n          <td class="num"><span>5,120</span></td>\n          <td class="num"><span>4,970</span></td>\n          <td class="num"><span>288,563</span></td>\n        </tr>\n\n        <tr>\n          <td align="center"><span class="date">2040.10.08</span></td>\n          <td class="num"><span>5,050</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            110\n                        </span>\n          </td>\n          <td class="num"><span>4,985</span></td>\n          <td class="num"><span>5,050</span></td>\n          <td class="num"><span>4,910</span></td>\n          <td class="num"><span>223,839</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.07</span></td>\n          <td class="num"><span>4,940</span></td>\n          <td class="num">\n            <img src="ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n                            70\n                        </span>\n          </td>\n          <td class="num"><span>4,990</span></td>\n          <td class="num"><span>5,110</span></td>\n          <td class="num"><span>4,905</span></td>\n          <td class="num"><span>199,580</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.04</span></td>\n          <td class="num"><span>5,010</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            90\n                        </span>\n          </td>\n          <td class="num"><span>4,900</span></td>\n          <td class="num"><span>5,050</span></td>\n          <td class="num"><span>4,900</span></td>\n          <td class="num"><span>188,467</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.02</span></td>\n          <td class="num"><span>4,920</span></td>\n          <td class="num">\n            <img src="ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n                            90\n                        </span>\n          </td>\n          <td class="num"><span>4,930</span></td>\n          <td class="num"><span>5,000</span></td>\n          <td class="num"><span>4,900</span></td>\n          <td class="num"><span>160,510</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.10.01</span></td>\n          <td class="num"><span>5,010</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            10\n                        </span>\n          </td>\n          <td class="num"><span>4,950</span></td>\n          <td class="num"><span>5,050</span></td>\n          <td class="num"><span>4,950</span></td>\n          <td class="num"><span>246,145</span></td>\n        </tr>\n\n        <tr>\n          <td align="center"><span class="date">2040.09.30</span></td>\n          <td class="num"><span>5,000</span></td>\n          <td class="num">\n            <img src="ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n                            10\n                        </span>\n          </td>\n          <td class="num"><span>5,180</span></td>\n          <td class="num"><span>5,300</span></td>\n          <td class="num"><span>4,990</span></td>\n          <td class="num"><span>705,046</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.09.27</span></td>\n          <td class="num"><span>5,010</span></td>\n          <td class="num">\n            <img src="ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n                            50\n                        </span>\n          </td>\n          <td class="num"><span>5,020</span></td>\n          <td class="num"><span>5,080</span></td>\n          <td class="num"><span>4,865</span></td>\n          <td class="num"><span>408,859</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.09.26</span></td>\n          <td class="num"><span>5,060</span></td>\n          <td class="num">\n            <span>0</span>\n          </td>\n          <td class="num"><span>5,130</span></td>\n          <td class="num"><span>5,200</span></td>\n          <td class="num"><span>4,965</span></td>\n          <td class="num"><span>404,633</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.09.25</span></td>\n          <td class="num"><span>5,060</span></td>\n          <td class="num">\n            <img src="ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n                            270\n                        </span>\n          </td>\n          <td class="num"><span>5,280</span></td>\n          <td class="num"><span>5,320</span></td>\n          <td class="num"><span>5,040</span></td>\n          <td class="num"><span>441,923</span></td>\n        </tr>\n        <tr>\n          <td align="center"><span class="date">2040.09.24</span></td>\n          <td class="num"><span>5,330</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            10\n                        </span>\n          </td>\n          <td class="num"><span>5,300</span></td>\n          <td class="num"><span>5,370</span></td>\n          <td class="num"><span>5,280</span></td>\n          <td class="num"><span>211,019</span></td>\n        </tr>\n      </tbody>\n    </table>\n  </div>\n  <div class="main container">\n    <h2 id="제주코딩베이스캠프공업">제주코딩베이스캠프 미디어</h2>\n    <table class="table table-hover">\n      <tbody>\n        <tr>\n          <th scope="col">날짜</th>\n          <th scope="col">종가</th>\n          <th scope="col">전일비</th>\n          <th scope="col">시가</th>\n          <th scope="col">고가</th>\n          <th scope="col">저가</th>\n          <th scope="col">거래량</th>\n        </tr>\n\n        <tr>\n          <td align="center"><span class="date">2040.10.23</span></td>\n          <td class="num"><span>31,300</span></td>\n          <td class="num">\n            <img src="ico_up.gif" width="7" height="6" style="margin-right:4px;" alt="상승"><span>\n                            100\n                        </span>\n          </td>\n          <td class="num"><span>31,150</span></td>\n          <td class="num"><span>31,850</span></td>\n          <td class="num"><span>30,450</span></td>\n          <td class="num"><span>513,365</span></td>\n        </tr>\n\n        <tr>\n          <td align="center"><span class="date">2040.10.22</span></td>\n          <td class="num"><span>31,200</span></td>\n          <td class="num">\n            <img src="ico_down.gif" width="7" height="6" style="margin-right:4px;" alt="하락"><span class="tah p11 nv01">\n                            100\n                        </span>\n          </td>\n          <td class="num"><span>31,450</span>

In [32]:
response = requests.get('http://www.paullab.co.kr/stock.html')
response.encoding = 'utf-8'
html = response.text

soup = BeautifulSoup(html, 'html.parser')

In [34]:
print(soup.prettify()) # html 문서 형식으로 출력

# 다운로드
# f = open('test.html', 'w', encoding='utf-8')
# f.write(html)
# f.close()

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="ie=edge" http-equiv="X-UA-Compatible"/>
  <title>
   크롤링 연습 페이지
  </title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"/>
  <link crossorigin="anonymous" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" rel="stylesheet" type="text/css"/>
  <style>
   h1{
      margin: 2rem;
    }

    h1>span{
      font-size: 1rem;
    }

    h2 {
      font-size: 1.5rem;
      font-weight: bold;
      margin-bottom: 1rem;
      margin-top: 5rem;
    }

    .heading-top {
      margin-top: 1rem;
    }

    .main {
      width: 100%;
      margin: 0 auto;
      text-align: center;
    }

    table {
      width: 100%;
    }

    a {
      /* color: inherit; */
      cursor: pointer;
      text-decoration: none;
    }

    a:hover {
      color: #000;
      text-decoration: none;
    }

    em {
      font: inherit;
    }

    #information {
      padding: 15px;
      margin-bottom: 50px;
    }

    #information h2 {
      padding-bottom: 20px;
    }

    #information .wrap {
      display: flex;
      align-items: center;

    }

    #information .cat-img img {
      width: 90%;
    }

    #information .tables {
      border: 1px solid #dbdbdb;
      padding: 20px 10px;
    }

    #information table {
      position: relative;
      width: 100%;
      padding: 10px;
      /* border-bottom: 1.5px dashed #dbdbdb; */
      align-items: center;
      border-collapse: separate;
    }

    #information tr {
      text-align: left;
      align-items: center;
    }

    #information th {
      font-size: 14px;
      align-items: center;
      padding-right: 10px;
      font-weight: normal;
    }

    #information td {
      text-align: right;
      font-size: 13px;
    }

    #information .strong {
      font-weight: bold;
    }

    .bar {
      color: #dbdbdb;
      font-size: 14px;
    }

    .link_site i {
      color: #000;
    }

    .link_site:hover {
      text-decoration: underline;
    }

    .link_site i {
      color: #dbdbdb;
      padding-left: 5px;
    }

    .help {
      font-size: 5px;
      font-weight: bold;
      color: rgb(91, 100, 103);
      border: 1px solid #888;
      padding: 0px 3px;
    }

    .lyr_section {
      position: absolute;
      font-size: 13px;
      background-color: #FFF;
      padding: 10px;
      width: 250px;
      border: 1px solid #888;
      line-height: 1.5;
      margin-top: 10px;
      z-index: 999;
    }

    #helpPannel5 p {
      color: #888;
      margin: 0;
    }

    .arrow {
      position: absolute;
      left: 75px;
      top: 0;
      width: 10px;
      height: 10px;
      border-top: 1px solid #888;
      border-right: 1px solid #888;
      background-color: #FFF;
      margin-top: -6px;
      -webkit-transform: rotate(-45deg);
      transform: rotate(-45deg);
    }

    .border-style {
      border-bottom: 1.5px dashed #dbdbdb;
    }
  </style>
 </head>
 <body>
  <!-- 메뉴바, 로고 이미지는 logo-icon.png -->
  <nav>
   <div class="container-fluid">
    <div class="row pt-3">
     <div class="col-12">
      <a href="https://www.paullab.co.kr">
       <img alt="logo" src="images/logo-icon.png" width="50px"/>
      </a>
     </div>
    </div>
   </div>
  </nav>
  <h1 class="sr-only">
   크롤링 연습용 페이지
  </h1>
  <div class="main container" id="information">
   <h2 class="heading-top">
    (주)캣네생선
   </h2>
   <p>
    해당 페이지는 주식 크롤링 연습용 페이지입니다. 책 크롤링 연습을 하고 싶다면
    <a href="https://paullab.co.kr/bookservice/">
     책 크롤링
    </a>
    페이지로 이동하세요.
   </p>
   <div class="wrap main row">
    <div class="cat-img col-md-7">
     <img alt="(주)캣네가게 주가" class="img-fluid" src="images/cats_stock.png"/>
    </div>
    <div class="tables col-md-5">
     <table class="border-style" summary="시가총액 정보">
      <tr>
       <th class="strong" scope="row">
        시가총액
       </th>
       <!-- 공백은 의도적으로 넣은 것입니다. -->
       <td class="strong">
        <em id="_market_sum">
         349조 2,323
        </em>
        억원
       </td>
      </tr>
      <tr>
       <th scope="row">
        <a class="link_site" href="#">
         시가총액순위
         <i class="fas fa-caret-right">
         </i>
        </a>
       </th>
       <!-- 공백은 의도적으로 넣은 것입니다. -->
       <td>
        위니브월드
        <em id="_market_sum">
         1
        </em>
        위
       </td>
      </tr>
      <tr>
       <th scope="row">
        상장주식수
       </th>
       <!-- 공백은 의도적으로 넣은 것입니다. -->
       <td>
        <em id="_market_sum">
         5,969,782,550
        </em>
       </td>
      </tr>
     </table>
     <table class="border-style" summary="업종상세 정보">
      <tr>
       <th class="strong" scope="row">
        현재가
       </th>
       <td class="strong">
        <em id="_market_sum">
         349조 2,323
        </em>
        억원
       </td>
      </tr>
      <tr>
       <th scope="row">
        52주 최고
        <span class="bar">
         l
        </span>
        최저
       </th>
       <td>
        <em>
         62,800
        </em>
        <span class="bar">
         l
        </span>
        <em>
         42,300
        </em>
       </td>
      </tr>
      <tr>
       <th scope="row">
        배당수익률
        <span class="bar">
         l
        </span>
        <span>
         2040.12
        </span>
        <a alt="배당수익률 상세설명" class="help" href="#">
         <em>
          ?
         </em>
        </a>
        <div class="lyr_section" style="display:none">
         <div class="tooltip_lyr dividend_layer" id="helpPannel5">
          <strong>
           배당수익률 = (배당금 / 현재가) x 100
          </strong>
          <p>
           배당금은 최근 결산연도 기준의 중간배당을 포함한 총 배당금입니다.
          </p>
          <span class="arrow">
          </span>
         </div>
        </div>
       </th>
       <td>
        <em id="_dvr">
         2.42
        </em>
        %
       </td>
      </tr>
     </table>
     <table>
      <tr>
       <th class="strong" scope="row">
        매출
       </th>
       <!-- <td>22조 1,250억원</td> -->
       <td class="strong">
        22,125,034,978,750원
       </td>
      </tr>
      <tr>
       <th scope="row">
        비용
       </th>
       <!-- <td>19조 2,238억원</td> -->
       <td>
        19,223,803,154,781원
       </td>
      </tr>
      <tr>
       <th scope="row">
        순익
       </th>
       <!-- <td><em id="_market_sum">2조 9,012억원</em></td> -->
       <td>
        <em id="_market_sum">
         2,901,231,823,969원
        </em>
       </td>
      </tr>
     </table>
    </div>
   </div>
  </div>
  <div class="main container">
   <h2 id="제주코딩베이스캠프연구원">
    제주코딩베이스캠프 연구원
   </h2>
   <table class="table table-hover">
    <tbody>
     <tr>
      <th scope="col">
       날짜
      </th>
      <th scope="col">
       종가
      </th>
      <th scope="col">
       전일비
      </th>
      <th scope="col">
       시가
      </th>
      <th scope="col">
       고가
      </th>
      <th scope="col">
       저가
      </th>
      <th scope="col">
       거래량
      </th>
     </tr>
     <tr>
      <td align="center ">
       <span class="date">
        2040.10.23
       </span>
      </td>
      <td class="num">
       <span>
        6,650
       </span>
      </td>
      <td class="num">
       <img alt="상승 " height="6 " src="ico_up.gif " style="margin-right:4px; " width="7 "/>
       <span>
        20
       </span>
      </td>
      <td class="num">
       <span>
        6,590
       </span>
      </td>
      <td class="num">
       <span>
        6,830
       </span>
      </td>
      <td class="num">
       <span>
        6,580
       </span>
      </td>
      <td class="num">
       <span>
        398,421
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.22
       </span>
      </td>
      <td class="num">
       <span>
        6,630
       </span>
      </td>
      <td class="num">
       <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/>
       <span class="tah p11 nv01">
        190
       </span>
      </td>
      <td class="num">
       <span>
        6,830
       </span>
      </td>
      <td class="num">
       <span>
        6,930
       </span>
      </td>
      <td class="num">
       <span>
        6,530
       </span>
      </td>
      <td class="num">
       <span>
        919,571
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.21
       </span>
      </td>
      <td class="num">
       <span>
        6,820
       </span>
      </td>
      <td class="num">
       <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/>
       <span>
        390
       </span>
      </td>
      <td class="num">
       <span>
        6,440
       </span>
      </td>
      <td class="num">
       <span>
        6,890
       </span>
      </td>
      <td class="num">
       <span>
        6,360
       </span>
      </td>
      <td class="num">
       <span>
        1,678,055
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.18
       </span>
      </td>
      <td class="num">
       <span>
        6,430
       </span>
      </td>
      <td class="num">
       <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/>
       <span>
        480
       </span>
      </td>
      <td class="num">
       <span>
        6,020
       </span>
      </td>
      <td class="num">
       <span>
        6,620
       </span>
      </td>
      <td class="num">
       <span>
        5,970
       </span>
      </td>
      <td class="num">
       <span>
        2,168,857
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.17
       </span>
      </td>
      <td class="num">
       <span>
        5,950
       </span>
      </td>
      <td class="num">
       <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/>
       <span>
        20
       </span>
      </td>
      <td class="num">
       <span>
        6,100
       </span>
      </td>
      <td class="num">
       <span>
        6,180
       </span>
      </td>
      <td class="num">
       <span>
        5,840
       </span>
      </td>
      <td class="num">
       <span>
        1,982,922
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.16
       </span>
      </td>
      <td class="num">
       <span>
        5,930
       </span>
      </td>
      <td class="num">
       <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/>
       <span>
        290
       </span>
      </td>
      <td class="num">
       <span>
        5,620
       </span>
      </td>
      <td class="num">
       <span>
        5,930
       </span>
      </td>
      <td class="num">
       <span>
        5,350
       </span>
      </td>
      <td class="num">
       <span>
        839,434
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.15
       </span>
      </td>
      <td class="num">
       <span>
        5,640
       </span>
      </td>
      <td class="num">
       <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/>
       <span>
        260
       </span>
      </td>
      <td class="num">
       <span>
        5,370
       </span>
      </td>
      <td class="num">
       <span>
        5,660
       </span>
      </td>
      <td class="num">
       <span>
        5,300
       </span>
      </td>
      <td class="num">
       <span>
        702,104
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.14
       </span>
      </td>
      <td class="num">
       <span>
        5,380
       </span>
      </td>
      <td class="num">
       <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/>
       <span>
        340
       </span>
      </td>
      <td class="num">
       <span>
        5,060
       </span>
      </td>
      <td class="num">
       <span>
        5,420
       </span>
      </td>
      <td class="num">
       <span>
        5,060
       </span>
      </td>
      <td class="num">
       <span>
        764,800
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.11
       </span>
      </td>
      <td class="num">
       <span>
        5,040
       </span>
      </td>
      <td class="num">
       <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/>
       <span class="tah p11 nv01">
        60
       </span>
      </td>
      <td class="num">
       <span>
        5,100
       </span>
      </td>
      <td class="num">
       <span>
        5,170
       </span>
      </td>
      <td class="num">
       <span>
        5,020
       </span>
      </td>
      <td class="num">
       <span>
        134,558
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.10
       </span>
      </td>
      <td class="num">
       <span>
        5,100
       </span>
      </td>
      <td class="num">
       <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/>
       <span>
        50
       </span>
      </td>
      <td class="num">
       <span>
        5,000
       </span>
      </td>
      <td class="num">
       <span>
        5,120
       </span>
      </td>
      <td class="num">
       <span>
        4,970
       </span>
      </td>
      <td class="num">
       <span>
        288,563
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.08
       </span>
      </td>
      <td class="num">
       <span>
        5,050
       </span>
      </td>
      <td class="num">
       <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/>
       <span>
        110
       </span>
      </td>
      <td class="num">
       <span>
        4,985
       </span>
      </td>
      <td class="num">
       <span>
        5,050
       </span>
      </td>
      <td class="num">
       <span>
        4,910
       </span>
      </td>
      <td class="num">
       <span>
        223,839
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.07
       </span>
      </td>
      <td class="num">
       <span>
        4,940
       </span>
      </td>
      <td class="num">
       <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/>
       <span class="tah p11 nv01">
        70
       </span>
      </td>
      <td class="num">
       <span>
        4,990
       </span>
      </td>
      <td class="num">
       <span>
        5,110
       </span>
      </td>
      <td class="num">
       <span>
        4,905
       </span>
      </td>
      <td class="num">
       <span>
        199,580
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.04
       </span>
      </td>
      <td class="num">
       <span>
        5,010
       </span>
      </td>
      <td class="num">
       <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/>
       <span>
        90
       </span>
      </td>
      <td class="num">
       <span>
        4,900
       </span>
      </td>
      <td class="num">
       <span>
        5,050
       </span>
      </td>
      <td class="num">
       <span>
        4,900
       </span>
      </td>
      <td class="num">
       <span>
        188,467
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.02
       </span>
      </td>
      <td class="num">
       <span>
        4,920
       </span>
      </td>
      <td class="num">
       <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/>
       <span class="tah p11 nv01">
        90
       </span>
      </td>
      <td class="num">
       <span>
        4,930
       </span>
      </td>
      <td class="num">
       <span>
        5,000
       </span>
      </td>
      <td class="num">
       <span>
        4,900
       </span>
      </td>
      <td class="num">
       <span>
        160,510
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.10.01
       </span>
      </td>
      <td class="num">
       <span>
        5,010
       </span>
      </td>
      <td class="num">
       <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/>
       <span>
        10
       </span>
      </td>
      <td class="num">
       <span>
        4,950
       </span>
      </td>
      <td class="num">
       <span>
        5,050
       </span>
      </td>
      <td class="num">
       <span>
        4,950
       </span>
      </td>
      <td class="num">
       <span>
        246,145
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.09.30
       </span>
      </td>
      <td class="num">
       <span>
        5,000
       </span>
      </td>
      <td class="num">
       <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/>
       <span class="tah p11 nv01">
        10
       </span>
      </td>
      <td class="num">
       <span>
        5,180
       </span>
      </td>
      <td class="num">
       <span>
        5,300
       </span>
      </td>
      <td class="num">
       <span>
        4,990
       </span>
      </td>
      <td class="num">
       <span>
        705,046
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.09.27
       </span>
      </td>
      <td class="num">
       <span>
        5,010
       </span>
      </td>
      <td class="num">
       <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/>
       <span class="tah p11 nv01">
        50
       </span>
      </td>
      <td class="num">
       <span>
        5,020
       </span>
      </td>
      <td class="num">
       <span>
        5,080
       </span>
      </td>
      <td class="num">
       <span>
        4,865
       </span>
      </td>
      <td class="num">
       <span>
        408,859
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.09.26
       </span>
      </td>
      <td class="num">
       <span>
        5,060
       </span>
      </td>
      <td class="num">
       <span>
        0
       </span>
      </td>
      <td class="num">
       <span>
        5,130
       </span>
      </td>
      <td class="num">
       <span>
        5,200
       </span>
      </td>
      <td class="num">
       <span>
        4,965
       </span>
      </td>
      <td class="num">
       <span>
        404,633
       </span>
      </td>
     </tr>
     <tr>
      <td align="center">
       <span class="date">
        2040.09.25
       </span>
      </td>
      <td class="num">
       <span>
        5,060
       </span>
      </td>
      <td class="num">
       <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/>
       <span class="tah p11 nv01">
        270
       </span>
      </td>
      <td class="num">
       <span>
        5,280
       </span>
      </td>
      <td class="num">
       <span>
        5,320
       </span>
      </td>
      <td class="num">
       <span>
        5,040
       </span>
      </td>

## BeautifulSoup
* str타입의 html 데이터를 html 구조를 가진 데이터로 가공해주는 라이브러리

In [35]:
soup.title

In [36]:
soup.title.string

'크롤링 연습 페이지'

In [37]:
soup.title.text

'크롤링 연습 페이지'

In [38]:
soup.tr

<tr>
<th class="strong" scope="row">시가총액</th>
<!-- 공백은 의도적으로 넣은 것입니다. -->
<td class="strong"><em id="_market_sum">349조 2,323</em>억원</td>
</tr>

In [39]:
soup.th

In [41]:
soup.find('th')

In [2]:
import requests
from bs4 import BeautifulSoup

In [9]:
soup = BeautifulSoup('''
<hojun id = 'jeju' class = 'codingBaseCamp codingLevelUp'>
    hello world
</hojun>
''')

tag = soup.hojun
tag

<hojun class="codingBaseCamp codingLevelUp" id="jeju">
    hello world
</hojun>

In [5]:
tag.name

'hojun'

In [10]:
tag['class']

['codingBaseCamp', 'codingLevelUp']

In [8]:
tag['id']

'jeju'

In [11]:
tag.attrs # id, class 확인

{'id': 'jeju', 'class': ['codingBaseCamp', 'codingLevelUp']}

In [12]:
tag.text

'\n    hello world\n'

In [13]:
for i in tag.children:
    print(i) # tag의 자식 출력

    hello world

In [14]:
soup = BeautifulSoup('''
<ul>
    <li id = 'jeju' class = 'codingBaseCamp codingLevelUp'>hello world</li>
    <li id = 'jeju' class = 'codingBaseCamp codingLevelUp'>hello world</li>
    <li id = 'jeju' class = 'codingBaseCamp codingLevelUp'>hello world</li>
<ul>
''')

tag = soup.ul
tag

<ul>
<li class="codingBaseCamp codingLevelUp" id="jeju">hello world</li>
<li class="codingBaseCamp codingLevelUp" id="jeju">hello world</li>
<li class="codingBaseCamp codingLevelUp" id="jeju">hello world</li>
<ul>
</ul></ul>

In [15]:
tag.contents # ul 태그를 제외하고 content만 출력

['\n',
 <li class="codingBaseCamp codingLevelUp" id="jeju">hello world</li>,
 '\n',
 <li class="codingBaseCamp codingLevelUp" id="jeju">hello world</li>,
 '\n',
 <li class="codingBaseCamp codingLevelUp" id="jeju">hello world</li>,
 '\n',
 <ul>
 </ul>]

In [16]:
tag.contents[1]

In [17]:
tag.li

In [18]:
tag.li.parent # 부모까지 출력

<ul>
<li class="codingBaseCamp codingLevelUp" id="jeju">hello world</li>
<li class="codingBaseCamp codingLevelUp" id="jeju">hello world</li>
<li class="codingBaseCamp codingLevelUp" id="jeju">hello world</li>
<ul>
</ul></ul>

## Selector
* 태그에 좀 더 세밀한 접근이 가능
* class를 지칭할 때는 '.'을 사용하고, id를 지칭할 때는 '#'를 사용
* 탐색하고자 하는 태그가 특정태그 하위에 있을때 '>'를 사용

In [19]:
import requests
from bs4 import BeautifulSoup

response = requests.get('http://www.paullab.co.kr/stock.html')

response.encoding = 'utf-8'
html = response.text

soup = BeautifulSoup(html, 'html.parser')

In [20]:
soup.select('#update')

[]

In [22]:
soup.select('.table > tbody > tr') # table class안에 tbody안에 모든 tr 태그 출력

[<tr>
 <th scope="col">날짜</th>
 <th scope="col">종가</th>
 <th scope="col">전일비</th>
 <th scope="col">시가</th>
 <th scope="col">고가</th>
 <th scope="col">저가</th>
 <th scope="col">거래량</th>
 </tr>,
 <tr>
 <td align="center "><span class="date">2040.10.23</span></td>
 <td class="num"><span>6,650</span></td>
 <td class="num">
 <img alt="상승 " height="6 " src="ico_up.gif " style="margin-right:4px; " width="7 "/><span>
                             20
                         </span>
 </td>
 <td class="num"><span>6,590</span></td>
 <td class="num"><span>6,830</span></td>
 <td class="num"><span>6,580</span></td>
 <td class="num"><span>398,421</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.22</span></td>
 <td class="num"><span>6,630</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             190
                         </span>
 </td>
 <td class="num"><span>6,830</span></td>
 <td class="num"><span>6,930</span></td>
 <td class="num"><span>6,530</span></td>
 <td class="num"><span>919,571</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.21</span></td>
 <td class="num"><span>6,820</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             390
                         </span>
 </td>
 <td class="num"><span>6,440</span></td>
 <td class="num"><span>6,890</span></td>
 <td class="num"><span>6,360</span></td>
 <td class="num"><span>1,678,055</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.18</span></td>
 <td class="num"><span>6,430</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             480
                         </span>
 </td>
 <td class="num"><span>6,020</span></td>
 <td class="num"><span>6,620</span></td>
 <td class="num"><span>5,970</span></td>
 <td class="num"><span>2,168,857</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.17</span></td>
 <td class="num"><span>5,950</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             20
                         </span>
 </td>
 <td class="num"><span>6,100</span></td>
 <td class="num"><span>6,180</span></td>
 <td class="num"><span>5,840</span></td>
 <td class="num"><span>1,982,922</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.16</span></td>
 <td class="num"><span>5,930</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             290
                         </span>
 </td>
 <td class="num"><span>5,620</span></td>
 <td class="num"><span>5,930</span></td>
 <td class="num"><span>5,350</span></td>
 <td class="num"><span>839,434</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.15</span></td>
 <td class="num"><span>5,640</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             260
                         </span>
 </td>
 <td class="num"><span>5,370</span></td>
 <td class="num"><span>5,660</span></td>
 <td class="num"><span>5,300</span></td>
 <td class="num"><span>702,104</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.14</span></td>
 <td class="num"><span>5,380</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             340
                         </span>
 </td>
 <td class="num"><span>5,060</span></td>
 <td class="num"><span>5,420</span></td>
 <td class="num"><span>5,060</span></td>
 <td class="num"><span>764,800</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.11</span></td>
 <td class="num"><span>5,040</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             60
                         </span>
 </td>
 <td class="num"><span>5,100</span></td>
 <td class="num"><span>5,170</span></td>
 <td class="num"><span>5,020</span></td>
 <td class="num"><span>134,558</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.10</span></td>
 <td class="num"><span>5,100</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             50
                         </span>
 </td>
 <td class="num"><span>5,000</span></td>
 <td class="num"><span>5,120</span></td>
 <td class="num"><span>4,970</span></td>
 <td class="num"><span>288,563</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.08</span></td>
 <td class="num"><span>5,050</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             110
                         </span>
 </td>
 <td class="num"><span>4,985</span></td>
 <td class="num"><span>5,050</span></td>
 <td class="num"><span>4,910</span></td>
 <td class="num"><span>223,839</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.07</span></td>
 <td class="num"><span>4,940</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             70
                         </span>
 </td>
 <td class="num"><span>4,990</span></td>
 <td class="num"><span>5,110</span></td>
 <td class="num"><span>4,905</span></td>
 <td class="num"><span>199,580</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.04</span></td>
 <td class="num"><span>5,010</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             90
                         </span>
 </td>
 <td class="num"><span>4,900</span></td>
 <td class="num"><span>5,050</span></td>
 <td class="num"><span>4,900</span></td>
 <td class="num"><span>188,467</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.02</span></td>
 <td class="num"><span>4,920</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             90
                         </span>
 </td>
 <td class="num"><span>4,930</span></td>
 <td class="num"><span>5,000</span></td>
 <td class="num"><span>4,900</span></td>
 <td class="num"><span>160,510</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.01</span></td>
 <td class="num"><span>5,010</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             10
                         </span>
 </td>
 <td class="num"><span>4,950</span></td>
 <td class="num"><span>5,050</span></td>
 <td class="num"><span>4,950</span></td>
 <td class="num"><span>246,145</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.09.30</span></td>
 <td class="num"><span>5,000</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             10
                         </span>
 </td>
 <td class="num"><span>5,180</span></td>
 <td class="num"><span>5,300</span></td>
 <td class="num"><span>4,990</span></td>
 <td class="num"><span>705,046</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.09.27</span></td>
 <td class="num"><span>5,010</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             50
                         </span>
 </td>
 <td class="num"><span>5,020</span></td>
 <td class="num"><span>5,080</span></td>
 <td class="num"><span>4,865</span></td>
 <td class="num"><span>408,859</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.09.26</span></td>
 <td class="num"><span>5,060</span></td>
 <td class="num">
 <span>0</span>
 </td>
 <td class="num"><span>5,130</span></td>
 <td class="num"><span>5,200</span></td>
 <td class="num"><span>4,965</span></td>
 <td class="num"><span>404,633</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.09.25</span></td>
 <td class="num"><span>5,060</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             270
                         </span>
 </td>
 <td class="num"><span>5,280</span></td>
 <td class="num"><span>5,320</span></td>
 <td class="num"><span>5,040</span></td>
 <td class="num"><span>441,923</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.09.24</span></td>
 <td class="num"><span>5,330</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             10
                         </span>
 </td>
 <td class="num"><span>5,300</span></td>
 <td class="num"><span>5,370</span></td>
 <td class="num"><span>5,280</span></td>
 <td class="num"><span>211,019</span></td>
 </tr>,
 <tr>
 <th scope="col">날짜</th>
 <th scope="col">종가</th>
 <th scope="col">전일비</th>
 <th scope="col">시가</th>
 <th scope="col">고가</th>
 <th scope="col">저가</th>
 <th scope="col">거래량</th>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.23</span></td>
 <td class="num"><span>31,300</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             100
                         </span>
 </td>
 <td class="num"><span>31,150</span></td>
 <td class="num"><span>31,850</span></td>
 <td class="num"><span>30,450</span></td>
 <td class="num"><span>513,365</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.22</span></td>
 <td class="num"><span>31,200</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             100
                         </span>
 </td>
 <td class="num"><span>31,450</span></td>
 <td class="num"><span>31,750</span></td>
 <td class="num"><span>30,100</span></td>
 <td class="num"><span>938,845</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.21</span></td>
 <td class="num"><span>31,300</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             500
                         </span>
 </td>
 <td class="num"><span>31,250</span></td>
 <td class="num"><span>32,800</span></td>
 <td class="num"><span>30,500</span></td>
 <td class="num"><span>1,774,049</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.18</span></td>
 <td class="num"><span>30,800</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             2,400
                         </span>
 </td>
 <td class="num"><span>28,700</span></td>
 <td class="num"><span>31,100</span></td>
 <td class="num"><span>28,400</span></td>
 <td class="num"><span>1,731,279</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.17</span></td>
 <td class="num"><span>28,400</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             700
                         </span>
 </td>
 <td class="num"><span>28,050</span></td>
 <td class="num"><span>29,200</span></td>
 <td class="num"><span>27,950</span></td>
 <td class="num"><span>983,611</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.16</span></td>
 <td class="num"><span>27,700</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             900
                         </span>
 </td>
 <td class="num"><span>27,900</span></td>
 <td class="num"><span>28,200</span></td>
 <td class="num"><span>27,300</span></td>
 <td class="num"><span>1,003,434</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.15</span></td>
 <td class="num"><span>26,800</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             700
                         </span>
 </td>
 <td class="num"><span>26,250</span></td>
 <td class="num"><span>27,000</span></td>
 <td class="num"><span>25,850</span></td>
 <td class="num"><span>589,982</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.14</span></td>
 <td class="num"><span>26,100</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             100
                         </span>
 </td>
 <td class="num"><span>26,500</span></td>
 <td class="num"><span>26,550</span></td>
 <td class="num"><span>25,750</span></td>
 <td class="num"><span>335,940</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.11</span></td>
 <td class="num"><span>26,200</span></td>
 <td class="num">
 <span>0</span>
 </td>
 <td class="num"><span>26,650</span></td>
 <td class="num"><span>26,700</span></td>
 <td class="num"><span>25,700</span></td>
 <td class="num"><span>531,894</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.10</span></td>
 <td class="num"><span>26,200</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             1,700
                         </span>
 </td>
 <td class="num"><span>24,750</span></td>
 <td class="num"><span>26,300</span></td>
 <td class="num"><span>24,700</span></td>
 <td class="num"><span>1,060,562</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.08</span></td>
 <td class="num"><span>24,500</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             850
                         </span>
 </td>
 <td class="num"><span>23,600</span></td>
 <td class="num"><span>24,600</span></td>
 <td class="num"><span>23,150</span></td>
 <td class="num"><span>336,803</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.07</span></td>
 <td class="num"><span>23,650</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             450
                         </span>
 </td>
 <td class="num"><span>24,200</span></td>
 <td class="num"><span>24,400</span></td>
 <td class="num"><span>23,550</span></td>
 <td class="num"><span>285,608</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.04</span></td>
 <td class="num"><span>24,100</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             400
                         </span>
 </td>
 <td class="num"><span>24,300</span></td>
 <td class="num"><span>24,700</span></td>
 <td class="num"><span>23,900</span></td>
 <td class="num"><span>236,640</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.02</span></td>
 <td class="num"><span>24,500</span></td>
 <td class="num">
 <span>0</span>
 </td>
 <td class="num"><span>24,100</span></td>
 <td class="num"><span>24,900</span></td>
 <td class="num"><span>24,000</span></td>
 <td class="num"><span>258,642</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.01</span></td>
 <td class="num"><span>24,500</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             400
                         </span>
 </td>
 <td class="num"><span>24,700</span></td>
 <td class="num"><span>25,200</span></td>
 <td class="num"><span>24,350</span></td>
 <td class="num"><span>368,213</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.09.30</span></td>
 <td class="num"><span>24,100</span></td>
 <td class="num">
 <img alt="상승" height="6" src="ico_up.gif" style="margin-right:4px;" width="7"/><span>
                             300
                         </span>
 </td>
 <td class="num"><span>23,300</span></td>
 <td class="num"><span>24,150</span></td>
 <td class="num"><span>22,950</span></td>
 <td class="num"><span>369,465</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.09.27</span></td>
 <td class="num"><span>23,800</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             300
                         </span>
 </td>
 <td class="num"><span>24,050</span></td>
 <td class="num"><span>24,600</span></td>
 <td class="num"><span>23,400</span></td>
 <td class="num"><span>300,900</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.09.26</span></td>
 <td class="num"><span>24,100</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             200
                         </span>
 </td>
 <td class="num"><span>24,650</span></td>
 <td class="num"><span>24,800</span></td>
 <td class="num"><span>23,850</span></td>
 <td class="num"><span>227,601</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.09.25</span></td>
 <td class="num"><span>24,300</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             1,200
                         </span>
 </td>
 <td class="num"><span>25,200</span></td>
 <td class="num"><span>25,450</span></td>
 <td class="num"><span>24,200</span></td>
 <td class="num"><span>367,106</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.09.24</span></td>
 <td class="num"><span>25,500</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             150
                         </span>
 </td>
 <td class="num"><span>25,650</span></td>
 <td class="num"><span>25,800</span></td>
 <td class="num"><span>25,150</span></td>
 <td class="num"><span>248,811</span></td>
 </tr>,
 <tr>
 <th scope="col">날짜</th>
 <th scope="col">종가</th>
 <th scope="col">전일비</th>
 <th scope="col">시가</th>
 <th scope="col">고가</th>
 <th scope="col">저가</th>
 <th scope="col">거래량</th>
 </tr>,
 <tr>
 <td align="center "><span class="date">2040.10.23</span></td>
 <td class="num"><span>13,250</span></td>
 <td class="num">
 <img alt="하락 " height="6 " src="ico_down.gif " style="margin-right:4px; " width="7 "/><span class="tah p11 nv01">
                             100
                         </span>
 </td>
 <td class="num"><span>13,400</span></td>
 <td class="num"><span>13,450</span></td>
 <td class="num"><span>13,150</span></td>
 <td class="num"><span>83,405</span></td>
 </tr>,
 <tr>
 <td align="center"><span class="date">2040.10.22</span></td>
 <td class="num"><span>13,350</span></td>
 <td class="num">
 <img alt="하락" height="6" src="ico_down.gif" style="margin-right:4px;" width="7"/><span class="tah p11 nv01">
                             150
                         </span>
 </td>
 <td class="num"><span>13,500</span></td>
 <td class="num"><span>13,600</span></td>
 <td class="num"><span>13,250</span></td>

In [ ]:
soup.select("p > a:nth-of-type(2)") # p태그 안에 a태그안에 2번째 요소 호출
soup.select("p > a:nth-of-type(2)") # p태그 안에 a태그안에 짝수 요소 호출
soup.select("#link1 + .sister") # id와 class를 동시에 가진 것을 호출

In [27]:
oneStep = soup.select('.main')[0]
oneStep

<div class="main container" id="information">
<h2 class="heading-top">(주)캣네생선</h2>
<p>해당 페이지는 주식 크롤링 연습용 페이지입니다. 책 크롤링 연습을 하고 싶다면 <a href="https://paullab.co.kr/bookservice/">책 크롤링</a> 페이지로 이동하세요.</p>
<div class="wrap main row">
<div class="cat-img col-md-7">
<img alt="(주)캣네가게 주가" class="img-fluid" src="images/cats_stock.png"/>
</div>
<div class="tables col-md-5">
<table class="border-style" summary="시가총액 정보">
<tr>
<th class="strong" scope="row">시가총액</th>
<!-- 공백은 의도적으로 넣은 것입니다. -->
<td class="strong"><em id="_market_sum">349조 2,323</em>억원</td>
</tr>
<tr>
<th scope="row">
<a class="link_site" href="#">시가총액순위<i class="fas fa-caret-right"></i></a>
</th>
<!-- 공백은 의도적으로 넣은 것입니다. -->
<td>위니브월드 <em id="_market_sum">1</em>위</td>
</tr>
<tr>
<th scope="row">상장주식수</th>
<!-- 공백은 의도적으로 넣은 것입니다. -->
<td><em id="_market_sum">5,969,782,550</em></td>
</tr>
</table>
<table class="border-style" summary="업종상세 정보">
<tr>
<th class="strong" scope="row">현재가</th>
<td class="strong"><em id="_market_sum">349조 2,323</em>억원</td>
</tr>
<tr>
<th scope="row">52주 최고 <span class="bar">l</span> 최저</th>
<td>
<em>62,800</em>
<span class="bar">l</span>
<em>42,300</em>
</td>
</tr>
<tr>
<th scope="row">배당수익률 <span class="bar">l</span><span> 2040.12</span>
<a alt="배당수익률 상세설명" class="help" href="#"><em>?</em></a>
<div class="lyr_section" style="display:none">
<div class="tooltip_lyr dividend_layer" id="helpPannel5">
<strong>배당수익률 = (배당금 / 현재가) x 100</strong>
<p>배당금은 최근 결산연도 기준의 중간배당을 포함한 총 배당금입니다.</p>
<span class="arrow"></span>
</div>
</div>
</th>
<td>
<em id="_dvr">2.42</em>%
                </td>
</tr>
</table>
<table>
<tr>
<th class="strong" scope="row">매출</th>
<!-- <td>22조 1,250억원</td> -->
<td class="strong">22,125,034,978,750원</td>
</tr>
<tr>
<th scope="row">비용</th>
<!-- <td>19조 2,238억원</td> -->
<td>19,223,803,154,781원</td>
</tr>
<tr>
<th scope="row">순익</th>
<!-- <td><em id="_market_sum">2조 9,012억원</em></td> -->
<td><em id="_market_sum">2,901,231,823,969원</em></td>
</tr>
</table>
</div>
</div>
</div>

In [ ]:
soup = BeautifulSoup('''
<hojun id = 'jeju' class = 'codingBaseCamp codingLevelUp'>
    hello world
</hojun>
''')

tag = soup.hojun
tag